deployment_name: concourse-production-pages
external_url: https://ci-pages.fr.cloud.gov
azs: [z2]
web_vm_type: m6i.large.concourse.web
worker_vm_type: m6i.xlarge.concourse.worker
iaas_worker_vm_type: m6i.xlarge.concourse.worker
web_vm_extensions: [production-concourse-pages-lb]
worker_vm_extensions: [production-concourse-profile]
iaas_worker_vm_extensions: [production-concourse-iaas-profile]
network_name: production-concourse-pages
web_instances: 2
worker_instances: 2
iaas_worker_instances: 1
build_logs_default: 25
build_logs_maximum: 0
max_active_containers_per_worker: 200